id: libconfig
version: 1.7.3
about: C/C++ configuration file library
depends:
  runtime:
    - gcc
    - texinfo
packages:
  - id: pkg
    dir: libconfig-1.7.3
    sources:
      - libconfig-1.7.3.tar.gz::https://github.com/hyperrealm/libconfig/archive/v1.7.3.tar.gz
    prescript: |
      autoreconf -fiv
    flags:
      - id: configurator
        value: configure