environ:
  - CFLAGS=-march=x86-64-v3 -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 --param=ssp-buffer-size=4
  - CXXFLAGS=-march=x86-64-v3 -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 --param=ssp-buffer-size=4
  - LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,--hash-style=gnu
  - MAKEFLAGS=-j8
  - ARCH=x86_64
mirrors:
  - https://storage.rlxos.dev/stable

container: itsmanjeet/devel-docker:2200-3

variables:
  prefix: "/usr"
  sysconfdir: "/etc"
  libexecdir: "/usr/lib"
  libdir: "/usr/lib"
  bindir: "/usr/bin"
  sbindir: "/usr/bin"
  datadir: "/usr/share"
  localstatedir: "/var"
  triplet: "x86_64-linux-gnu"

  arch: "x86_64"

build-tools:
  - id: meson
    target-files:
      - meson.build
    script: |
      meson %{build-dir}                \
        --prefix=%{prefix}              \
        --sysconfdir=%{sysconfdir}      \
        --libdir=%{libdir}              \
        --libexecdir=%{libexecdir}      \
        --bindir=%{bindir}              \
        --datadir=%{datadir}            \
        --localstatedir=%{localstatedir}  \
        --sbindir=%{sbindir} %{configure}

      ninja -C %{build-dir} %{compile}
      DESTDIR=%{install-root} ninja -C %{build-dir} install %{install}

  - id: pysetup
    target-files:
      - setup.py

    script: |
      python3 setup.py build %{compile}
      python3 setup.py install --root=%{install-root} %{install} --optimize=1

  - id: cmake
    target-files:
      - CMakeLists.txt

    script: |
      cmake -B %{build-dir}                       \
        -DCMAKE_INSTALL_PREFIX=%{prefix}          \
        -DCMAKE_INSTALL_SYSCONFDIR=%{sysconfdir}  \
        -DCMAKE_INSTALL_BINDIR=%{bindir}          \
        -DCMAKE_INSTALL_SBINDIR=%{sbindir}        \
        -DCMAKE_INSTALL_LIBDIR=%{libdir}          \
        -DCMAKE_INSTALL_LIBEXECDIR=%{libexecdir}  \
        -DCMAKE_INSTALL_LOCALSTATEDIR=%{localstatedir}  \
        -DCMAKE_INSTALL_DATADIR=%{datadir}  \
        -DCMAKE_BUILD_TYPE=Release

      cmake --build %{build-dir} %{compile}
      DESTDIR=%{install-root} cmake --install %{build-dir} %{install}

  - id: autotools
    target-files:
      - configure
      - autogen.sh

    script: |
      if [ -z $NO_BUILD_DIR ] ; then
          mkdir -p %{build-dir}
      fi

      if [ -e ./autogen.sh ] ; then
          ./autogen.sh
      fi

      exec="./configure"
      if [ -z $NO_BUILD_DIR ] ; then
          cd %{build-dir}
          exec="../configure"
      fi
      $exec --prefix=%{prefix}            \
          --sysconfdir=%{sysconfdir}      \
          --libdir=%{libdir}              \
          --libexecdir=%{libexecdir}      \
          --bindir=%{bindir}              \
          --datadir=%{datadir}            \
          --host=%{triplet}               \
          --build=%{triplet}              \
          --localstatedir=%{localstatedir}  \
          --sbindir=%{sbindir} %{configure}

      make -j4 %{compile}
      make install %{install} DESTDIR=%{install-root}
