merge: [version.yml]
build-type: system

variables:
  force-rebuild: true
  liveuser: "liveuser"

build-time:
  - components/squashfs-tools.yml

pre-script: |
  # Create Live User
  install -vDm 0644 /dev/stdin %{install-root}/lib/systemd/system/live-user.service << "EOF"
  [Unit]
  Description=Create Live User
  Before=graphical.target
  After=systemd-tmpfiles-setup.service
  

  [Service]
  Type=simple
  ExecStart=/usr/bin/useradd -g users -G wheel,adm -m %{liveuser}

  [Install]
  WantedBy=default.target
  EOF

  install -vDm 0644 /dev/stdin %{install-root}/lib/tmpfiles.d/%{liveuser}.conf << "EOF"
  C %{sysconfdir}/lightdm/lightdm.conf.d/12-autologin.conf
  C %{sysconfdir}/sudoers.d/%{liveuser}
  EOF

  # Authenticate to run sudo commands without password
  install -vDm 0644 /dev/stdin %{install-root}/share/factory/etc/sudoers.d/%{liveuser} << "EOF"
  %{liveuser} ALL=(ALL) NOPASSWD: ALL
  EOF

  # AutoLogin to Live User
  install -vDm 0644 /dev/stdin %{install-root}/share/factory/etc/lightdm/lightdm.conf.d/12-autologin.conf << "EOF"
  [SeatDefaults]
  autologin-user=%{liveuser}
  autologin-user-timeout=0
  autologin-session=xfce
  EOF

  # Create Installation Guide
  install -vDm 0644 /dev/stdin %{install-root}/share/factory/etc/skel/Desktop/README << "EOF"
  RLXOS GNU/Linux %{version} %{codename}

  Notes
  - Root password: 'root'
  - Live User Password: Need to set
  - Live User Have access to sudo commands without password

  Installation
  - %{bindir}/swupd clone is a CLI tool to help installation of rlxos.
  - You need a blank ext4 partition of size atleast 4 GiB
  - You might also need a EFI parition for UEFI boot support (LABEL=EFI)
  - Execute below command with your path to partition (not DISK).
  - $ %{bindir}/clone /run/iso/sysroot.img install /dev/sd?
  - reboot once installation done
  EOF
