merge: [version.yml]
build-type: system

depends:
  - components/installer.yml

build-time:
  - components/squashfs-tools.yml

pre-script: |
  mkdir -p %{install-root}/%{sysconfdir}/systemd/system/getty@tty1.service.d/
  cat >%{install-root}/%{sysconfdir}/systemd/system/getty@tty1.service.d/autologin.conf << EOF
  [Service]
  ExecStart=
  ExecStart=-/sbin/agetty -o '-p -f -- \\u' --noclear --autologin root %I $TERM
  EOF

  cp -rap %{install-root}/%{prefix}/* %{install-root}/
  rm -rf %{install-root}/%{prefix}