id: kconfigwidgets
version: 5.94.0
about: KF5 kconfigwidgets
depends:
  runtime:
    - kauth
    - kcodecs
    - kconfig
    - kguiaddons
    - ki18n
    - kwidgetsaddons
  buildtime:
    - extra-cmake-modules
    - perl
    - kdoctools
sources:
    - https://download.kde.org/stable/frameworks/5.94/{{id}}-{{version}}.tar.xz

configure: >
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_TESTING=OFF
    -Wno-dev
