id: xfce4-settings
version: 4.16.2
release: 2
about: collection of programs to adjust xfce preferences
depends:
  runtime:
    - exo
    - garcon
    - xfconf
    - libcanberra
    - libnotify
    - libxklavier
    - colord
    - libinput
    - upower
  buildtime:
    - intltool
    - xorg-drivers-input
sources:
  - https://archive.xfce.org/src/xfce/xfce4-settings/4.16/xfce4-settings-{{version}}.tar.bz2
pre-script: |
  patch xfsettingsd/xsettings.xml < ${FILES_DIR}/rlxos-theming.patch
configure: >
  --enable-sound-settings
  --enable-pluggable-dialogs