distribution_name: 'rlxos'
internet_connection_required: no
suggested_languages:
  - 'hi'
  - 'ar'
  - 'de'
  - 'en'
  - 'es'
  - 'fr'
  - 'ja'
  - 'ru'
  - 'zh'

welcome_page:
  logo: 'start-here'


minimum_disk_size: 5

offer_disk_encryption: no
skip_user: yes
skip_locale: yes

browser_cmd: 'firefox'
disks_cmd: 'sudo gparted'
wifi_cmd: 'nm-connection-editor'