id: systemsettings
version: 5.24.5
about: Plasma systemsettings
depends:
  runtime:
    - plasma-workspace
  buildtime:
    - extra-cmake-modules
    - kdoctools
sources:
    - https://download.kde.org/stable/plasma/{{version}}/{{id}}-{{version}}.tar.xz

configure: >
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_TESTING=OFF
    -Wno-dev
