id: gnome-settings-daemon
version: 40.0.1
about: |
  Daemon responsible for setting various parameters of a GNOME Session

depends:
  runtime:
    - alsa-lib
    - colord
    - fontconfig
    - gcr
    - geoclue
    - geocode-glib
    - gnome-desktop
    - lcms
    - libcanberra
    - libgweather
    - libnotify
    - librsvg
    - libwacom
    - pulseaudio
    - systemd
    - upower
    - alsa-lib
    - cups
    - networkmanager
    - nss
    - wayland

sources:
  - https://download.gnome.org/sources/gnome-settings-daemon/40/gnome-settings-daemon-40.0.1.tar.xz

packages:
  - id: pkg
    dir: gnome-settings-daemon-40.0.1
    flags:
      - id: configure
        value: >
          --buildtype=release
          -Dwwan=false
