id: gsettings-desktop-schemas
version: "40.0"
about: GSettings Desktop Schemas package contains a collection of GSettings schemas
  for settings shared by various components of a GNOME Desktop
release: 0
depends:
- components/glib.yml
- components/gobject-introspection.yml
sources:
- https://download.gnome.org/sources/gsettings-desktop-schemas/40/gsettings-desktop-schemas-40.0.tar.xz
pre-script: |-
  sed -i -r "s:\"(/system):\"/org/gnome\\1:g" schemas/*.in
  patch schemas/org.gnome.desktop.background.gschema.xml.in < /files/gsettings-desktop-schemas/background-default.patch
  patch schemas/org.gnome.desktop.interface.gschema.xml.in < /files/gsettings-desktop-schemas/themes.patch

