id: kde-gtk-config
version: 5.24.5
about: Plasma kde-gtk-config
release: 0
depends:
- components/kconfigwidgets.yml
- components/kdbusaddons.yml
- components/kdecoration.yml
- components/gtk.yml
- components/gsettings-desktop-schemas.yml
build-time:
- components/extra-cmake-modules.yml
- components/sassc.yml
sources:
- https://download.kde.org/stable/plasma/%{version}/%{id}-%{version}.tar.xz
configure: |
  -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -Wno-dev

