id: nvidia-settings
version: 515.65.01
about: Tool for configuring the NVIDIA graphics driver
depends:
  runtime:
    - gtk
    - jansson
    - libvdpau
    - libXv
    - nvidia-utils
  buildtime:
    - gtk2
    - inetutils
    - jansson
    - libvdpau
    - libxext

sources:
  - nvidia-settings-{{version}}.tar.gz::https://github.com/NVIDIA/nvidia-settings/archive/{{version}}.tar.gz
build-dir: nvidia-settings-{{version}}

script: |
  patch -p0 < ${FILES_DIR}/libxnvctrl_so.patch
  make
  make -C src/libXNVCtrl
  make DESTDIR=${pkgupd_pkgdir} install

  install -D -m644 doc/nvidia-settings.desktop "${pkgupd_pkgdir}/usr/share/applications/nvidia-settings.desktop"
  install -D -m644 doc/nvidia-settings.png "${pkgupd_pkgdir}/usr/share/pixmaps/nvidia-settings.png"
  sed \
    -e 's:__UTILS_PATH__:/usr/bin:' \
    -e 's:__PIXMAP_PATH__:/usr/share/pixmaps:' \
    -e 's/__NVIDIA_SETTINGS_DESKTOP_CATEGORIES__/Settings;HardwareSettings;/' \
    -e 's/Icon=.*/Icon=nvidia-settings/' \
    -i "${pkgupd_pkgdir}/usr/share/applications/nvidia-settings.desktop"

  cd src/libXNVCtrl
  install -Dm 644 ./*.h -t "${pkgupd_pkgdir}/usr/include/NVCtrl"
  install -d "${pkgupd_pkgdir}/usr/lib"
  cp -Pr _out/Linux_x86_64/libXNVCtrl.* -t "${pkgupd_pkgdir}/usr/lib"