id: systemsettings
version: 5.24.5
about: Plasma systemsettings
release: 0
depends:
- components/plasma-workspace.yml
build-time:
- components/extra-cmake-modules.yml
- components/kdoctools.yml
sources:
- https://download.kde.org/stable/plasma/%{version}/%{id}-%{version}.tar.xz
configure: |
  -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -Wno-dev

