id: xfce4-settings
version: 4.18.3
about: collection of programs to adjust xfce preferences

depends:
  - components/exo.yml
  - components/garcon.yml
  - components/xfconf.yml
  - components/libcanberra.yml
  - components/libnotify.yml
  - components/x11/libxklavier.yml
  - components/colord.yml
  - components/libinput.yml
  - components/upower.yml
build-time:
  - components/intltool.yml
  - components/x11/xf86-input-libinput.yml
sources:
  - https://archive.xfce.org/src/xfce/xfce4-settings/%{version:1}/xfce4-settings-%{version}.tar.bz2

configure: >-
  --enable-sound-settings
  --enable-pluggable-dialogs
