id: xkeyboard-config
version: 2.39
about: Keyboard configuration database for the X Window System
sources:
  - https://xorg.freedesktop.org/archive/individual/data/%{id}/%{id}-%{version}.tar.xz

build-time:
  - core/libxslt.yml
  - core/meson.yml
  - core/python.yml
