id: pkg-config
version: 1.8.1
about: Tool for passing the include path and/or library paths to build tools during the configure and make phases of package installations

configure: >-
  -D tests=false
sources:
  - https://gitea.treehouse.systems/ariadne/pkgconf/archive/pkgconf-%{version}.tar.gz

depends:
  - components/core/glibc.yml
