id: docker
version: 20.10.7
release: 2
about: Pack, ship and run any application as a lightweight container
depends:
  buildtime:
    - containerd
    - runc
    - lvm2
    - btrfs-progs
    - cgroupfs-mount
    - go
    - appimagetool

type: app
sources:
  - https://github.com/moby/moby/archive/v{{version}}/moby-{{version}}.tar.gz
  - https://github.com/docker/cli/archive/v{{version}}/cli-{{version}}.tar.gz
  - libnetwork-0.3.tar.gz::https://github.com/moby/libnetwork/archive/refs/heads/master.tar.gz


environ:
  - GO111MODULE=auto
  - DOCKER_GITCOMMIT=b0f5bc3
  - DOCKER_BUILDTAGS='seccomp'
  - DISABLE_WARN_OUTSIDE_CONTAINER=1
build-dir: .
script: |
  export GOPATH=${pkgupd_srcdir}
  mkdir -p src/github.com/docker
  cd src/github.com/docker
  ln -s ${pkgupd_srcdir}/cli-{{version}} cli
  cd cli
  make VERSION={{version}} dynbinary
  
  cd ../
  ln -s ${pkgupd_srcdir}/moby-{{version}} docker
  cd docker
  VERSION={{version}} hack/make.sh dynbinary
  ls -al bundles/dynbinary-daemon/
  cd ../
  ln -s ${pkgupd_srcdir}/libnetwork-master libnetwork
  #ls -al libnetwork/	
  cd libnetwork/cmd/proxy
  GOROOT=/usr/lib/go go build -o ${pkgupd_pkgdir}/usr/bin/docker-proxy
  
  cd ${pkgupd_srcdir}
  
  install -D -m 0755 cli-{{version}}/build/docker ${pkgupd_pkgdir}/usr/bin/docker
  install -D -m 0755 moby-{{version}}/bundles/dynbinary-daemon/dockerd-{{version}} \
    ${pkgupd_pkgdir}/usr/bin/dockerd
    
    #  for M in 1 5 8 ; do
    #install -d -m 0755 ${pkgupd_pkgdir}/usr/share/man/man${M}
    #install -m 0644 ${pkgupd_srcdir}/man${M}/* ${pkgupd_pkgdir}/usr/share/man/man${M}
    #done
  
  ln -s containerd ${pkgupd_pkgdir}/usr/bin/docker-containerd
  ln -s containerd-shim ${pkgupd_pkgdir}/usr/bin/docker-containerd-shim
  ln -s ctr ${pkgupd_pkgdir}/usr/bin/docker-containerd-ctr
  ln -s runc ${pkgupd_pkgdir}/usr/bin/docker-runc
  
  install -D -m 0755 moby-{{version}}/contrib/check-config.sh \
    ${pkgupd_pkgdir}/usr/share/docker/check-config.sh
  
  install -D -m 0755 moby-{{version}}/contrib/init/systemd/docker.{service,socket} \
    -t ${pkgupd_pkgdir}/usr/lib/systemd/system/
  
  install -D -m 0644 moby-{{version}}/contrib/udev/80-docker.rules \
    ${pkgupd_pkgdir}/usr/lib/udev/rules.d/80-docker.rules


  # include required
  for i in containerd ctr containerd-shim \
    containerd-shim-runc-v1 containerd-shim-runc-v2 \
    runc cgroupfs-mount cgroupfs-umount; do
    install -v -D -m 0755 /usr/bin/${i} \
      -t ${pkgupd_pkgdir}/usr/bin/
  done

  # install appimage requirements
  install -v -D -m 0755 ${FILES_DIR}/AppRun -t ${pkgupd_pkgdir}/
  install -v -D -m 0644 ${FILES_DIR}/{{id}}.desktop -t ${pkgupd_pkgdir}/
  install -v -D -m 0644 ${FILES_DIR}/{{id}}.png -t ${pkgupd_pkgdir}/