id: libconfig
version: 1.7.3
about: C/C++ configuration file library
sources:
- libconfig-1.7.3.tar.gz::https://github.com/hyperrealm/libconfig/archive/v1.7.3.tar.gz
build-dir: libconfig-1.7.3
depends:
  buildtime:
  - texinfo
pre-script: 'autoreconf -fiv

  '
