name: Build and Release
on:
  push:

jobs:
  generate-image:
    name: Generate Image
    runs-on: self-hosted
    timeout-minutes: 46000
    strategy:
      matrix:
        board:
          - amd64
    env:
      CACHE_PATH: ${{ secrets.CACHE_PATH }}
      BUILDER: ./builder -cache-path ${{ secrets.CACHE_PATH }}
    steps:
      - uses: actions/checkout@v1
      - name: Building pkgupd-builder
        run: |
          go mod tidy
          go mod vendor
          go build -o builder rlxos/cmd/builder

      - name: Generating Board Image
        run: ${BUILDER} build boards/${{matrix.board}}/image.yml

      - name: Generating Updates
        run: ${BUILDER} build boards/${{matrix.board}}/updates.yml
      
      - name: Checkout Updatess
        run: ${BUILDER} checkout boards/${{matrix.board}}/updates.yml ${CACHE_PATH}/daily/

      - name: Generating Installer image
        run: ${BUILDER} build boards/${{matrix.board}}/installer.yml
      
      - name: Checkout Installer image
        run: ${BUILDER} checkout boards/${{matrix.board}}/installer.yml ${CACHE_PATH}/daily/
