name: Build Package
on:
  workflow_dispatch:
    inputs:
      recipe_file:
        required: true
      repository:
        required: true
        default: testing
      version:
        required: true
        default: 2200
  push:
    paths:
      - 'recipes/**'
    branches-ignore:
      - master
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 43800
    container:
      image: itsmanjeet/rlxos-devel:2200-1
      volumes:
        - /storage/${{ github.event.inputs.repository }}/${{ github.event.inputs.version }}/pkgs/:/var/cache/pkgupd/pkgs/
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Update system
        run: NO_INPUT=1 PKGUPD_NO_PROGRESS=1 PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml pkgupd update mode.ask=false
      
      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        if: ${{ github.event.action }} == 'push'

      - name: Compile Packages
        run: |
          changed_file="${{github.event.inputs.recipe_file}}"
          [[ -z ${changed_file} ]] && changed_file="${{ steps.changed-files.outputs.all }}"
          for recipe in ${changed_file} ; do
            echo "compiling ${recipe}"
            PKGUPD_NO_PROGRESS=1 \
              PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml \
              NO_INPUT=1 \
              pkgupd build ${recipe}
          done

      - name: Update Repository
        run: |
          PKGUPD_NO_PROGRESS=1 \
            PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml \
            NO_INPUT=1 \
            pkgupd meta