name: Build Package
on:
  workflow_dispatch:
    inputs:
      recipe_file:
        required: true
      repository:
        required: true
        default: testing
      version:
        required: true
        default: 2200
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 43800
    container:
      image: itsmanjeet/rlxos-devel:2200-1
      volumes:
        - ${{ secrets.STORAGE_DIR }}/${{ github.event.inputs.repository }}/${{ github.event.inputs.version }}/pkgs/:/var/cache/pkgupd/pkgs/
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Update system
        run: NO_INPUT=1 PKGUPD_NO_PROGRESS=1 PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml pkgupd update mode.ask=false

      - name: Compile Packages
        run: |
          changed_file="${{github.event.inputs.recipe_file}}"
          echo "compiling ${changed_file}"
          PKGUPD_NO_PROGRESS=1 \
            PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml \
            NO_INPUT=1 \
            pkgupd build ${changed_file}

      - name: Update Repository
        run: |
          PKGUPD_NO_PROGRESS=1 \
            PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml \
            NO_INPUT=1 \
            pkgupd meta