name: Build Package
on:
  push:
    paths:
      - 'recipes/**'
    branches-ignore:
      - master
env:
  NO_INPUT: 1
  PKGUPD_NO_PROGRESS: 1

jobs:
  check-changes:
    if: ${{ github.event.action }} == 'push'
    runs-on: self-hosted
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all }}
    container:
      image: itsmanjeet/rlxos-devel:2200-1

    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1

  build:
    runs-on: self-hosted
    needs: [check-changes]
    timeout-minutes: 43800
    container:
      image: itsmanjeet/rlxos-devel:2200-1
      volumes:
        - /storage/testing/2200/pkgs/:/var/cache/pkgupd/pkgs/
      options: --privileged
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Update system
        run: |
          export PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml 
          pkgupd update mode.ask=false
          # temporary reupdate for updated pkgupd database
          pkgupd update mode.ask=false
          pkgupd install squashfs-tools mode.ask=false
      
      - name: Compile Packages
        id: compiled-package
        run: |
          changed_file="${{needs.check-changes.outputs.changed_files}}"
          for recipe in ${changed_file} ; do
            if [[ ${recipe} =~ recipes/ ]] && [[ "${recipe}" == *.yml ]] && [[ -e ${recipe} ]] ; then
              echo "compiling ${recipe}"
              PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml \
                pkgupd build ${PWD}/${recipe} \
                build.repository=$(echo ${recipe} | cut -d '/' -f2)
            fi
          done

  update-repository:
    runs-on: self-hosted
    needs: [build]
    timeout-minutes: 43800
    container:
      image: itsmanjeet/rlxos-devel:2200-1
      volumes:
        - /storage/testing/2200/pkgs/:/var/cache/pkgupd/pkgs/

    steps:
      - uses: actions/checkout@v2

      - name: Update system
        run: |
          export PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml 
          pkgupd update mode.ask=false
          pkgupd install squashfs-tools mode.ask=false
      
      - name: Update Repository
        run: |
          PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml \
            pkgupd meta

  update-bazaar:
    runs-on: self-hosted
    needs: [build, check-changes]
    timeout-minutes: 43800
    container:
      image: itsmanjeet/rlxos-devel:2200-1
      volumes:
        - /storage/testing/2200/pkgs/:/var/cache/pkgupd/pkgs/

    steps:
      - uses: actions/checkout@v2

      - name: Update system
        run: |
          export PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml 
          pkgupd update mode.ask=false
          pkgupd install py-pip mode.ask=false
          pip install woocommerce pyyaml
      
      - name: Update Bazaar
        run: |
          changed_file="${{needs.check-changes.outputs.changed_files}}"
          for recipe in ${changed_file} ; do
            if [[ ${recipe} =~ recipes/ ]] && [[ "${recipe}" == *.yml ]] && [[ -e ${recipe} ]] ; then
              ./scripts/update-bazaar.py /var/cache/pkgupd/pkgs/$(dirname $(echo ${recipe} | cut -d '/' -f2-)).meta ${recipe}
            fi
          done
          
        env:
          BAZAAR_ID: ${{ secrets.BAZAAR_ID }}
          BAZAAR_KEY: ${{ secrets.BAZAAR_KEY }}

  