name: Build and Release
on:
  push:

jobs:
  generate-image:
    name: Generate Image
    runs-on: self-hosted
    timeout-minutes: 46000
    strategy:
      matrix:
        board:
          - amd64-core
    env:
      CACHE_PATH: ${{ secrets.CACHE_PATH }}
    steps:
      - uses: actions/checkout@v1
      - name: Generating Board Image
        run: |
          go run rlxos/cmd/pkgupd-builder -cache-path ${CACHE_PATH} build boards/${{matrix.board}}/image.yml
      - name: Generating Installer image
        run: |
          go run rlxos/cmd/pkgupd-builder -cache-path ${CACHE_PATH} build boards/${{matrix.board}}/installer.yml
