name: Build and Release
on:
  push:
    tags:
      - '*'
    branches:
      - 'rolling'
jobs:
  generate-image:
    name: Generate Image
    runs-on: self-hosted
    timeout-minutes: 46000
    strategy:
      matrix:
        board:
          - x86_64
    env:
      CACHE_PATH: ${{ secrets.CACHE_PATH }}
      SERVER: ${{ secrets.SERVER }}
    steps:
      - uses: actions/checkout@v1


      - name: Setup Environment
        run: |
          TAG_NAME=${GITHUB_REF#refs/*/}
          VERSION="$(echo ${TAG_NAME} | cut -d '-' -f1)"
          CODENAME="$(echo ${TAG_NAME} | cut -d '-' -f2-)"

          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

          [[ "${TAG_NAME}" -eq "rolling" ]] && {
            VERSION=999
            CODENAME="rolling"
          }
          echo "ARCH=${{matrix.board}}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}"   >> $GITHUB_ENV
          echo "CODENAME=${CODENAME}" >> $GITHUB_ENV

          echo "NO CHANGELOG" > files/changelog

      - name: Cleanup build cache
        run: make clean
      
      - name: Make Board Image
        run: |
          for element in image live-config installer updates ; do
            make component ELEMENT=boards/${{matrix.board}}/${element}.yml
          done

      - name: Checkout Release
        run: |
          make checkout ELEMENT=boards/${{matrix.board}}/installer.yml RELEASE_PATH=${CACHE_PATH}/releases/
          make checkout ELEMENT=boards/${{matrix.board}}/updates.yml   RELEASE_PATH=${RELEASE_PATH}/updates/