name: Build and Release
on:
  push:

jobs:
  generate-image:
    name: Generate Image
    runs-on: self-hosted
    timeout-minutes: 46000
    strategy:
      matrix:
        board:
          - amd64
    env:
      CACHE_PATH: ${{ secrets.CACHE_PATH }}
      BUILDER: ./builder -cache-path ${{ secrets.CACHE_PATH }}
    steps:
      - uses: actions/checkout@v1
      - name: Building pkgupd-builder
        run: go build -o builder rlxos/cmd/builder

      - name: Generating Board Image
        run: ${BUILDER} build boards/${{matrix.board}}/image.yml

      - name: Generating Installer image
        run: ${BUILDER} build boards/${{matrix.board}}/installer.yml
      
      - name: Checkout Installer image
        run: installer_image=$(${BUILDER} file boards/${{matrix.board}}/installer.yml) && tar -xf $installer_image -C ${CACHE_PATH}/daily/
