name: build package trigger
on:
  push:
    paths:
      - 'recipes/**'
    branches-ignore:
      - master
  workflow_dispatch:
    inputs:
      recipefile:
        required: true
        type: string
env:
  PKGUPD_NO_PROGRESS: 1

jobs:
  build:
    runs-on: self-hosted
    container:
      image: itsmanjeet/devel-docker:2200-3
      volumes:
        - /storage:/storage
        - /var/run/docker.sock:/var/run/docker.sock
      privileged: true
    steps:
      - uses: actions/checkout@v2

      - name: get changes
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        if: github.event_name == 'push'

      - name: prerequisite
        run: |
          ln -srfv ./pkgupd.yml /etc/pkgupd.yml
          mkdir -p /var/lib/pkgupd/data
          pkgupd update mode.ask=false
          pkgupd install squashfs-tools rlxos-build-tools mtools mode.ask=false

      - name: build changes
        run: |
          export TELEGRAM_TO=${{ secrets.TELEGRAM_TO }}
          export TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          export BAZAAR_ID=${{ secrets.BAZAAR_ID }}
          export BAZAAR_KEY=${{ secrets.BAZAAR_KEY }}
          
          if [[ "${{github.event_name}}" == 'push' ]] ; then
            recipefile="${{steps.changed-files.outputs.all}}"
          else
            recipefile="${{github.event.inputs.recipefile}}"
          fi

          for recipe in ${recipefile} ; do
            if [[ ${recipe} =~ recipes/ ]] && [[ "${recipe}" == *.yml ]] && [[ -e ${recipe} ]] ; then
              ./build.sh build ${recipe} --debug --pkgupd-path /storage/
            fi
          done

      - name: sync
        run: |
          ./build.sh refresh --debug --pkgupd-path /storage/