name: Build and Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  NO_PRINT_PROGRESS: 1
  INGITE: ./ignite

jobs:
  generate-image:
    name: Generate Image
    runs-on: rlxos-server
    timeout-minutes: 47000
    strategy:
      matrix:
        board:
          - amd64
    steps:
      - uses: actions/checkout@v1

      - name: Compiler Ignite
        run: |
          make

      - name: Prerequisties
        run: |
          echo "version: ${GITHUB_REF#refs/*/}" > version.yml

      - name: Generate Element Cache
        run: |
          for element in apps liveconfig usr image ; do
            ${INGITE} build boards/${{matrix.board}}/${element}.yml
          done

      - name: Checkout System Image and Installer ISO
        run: |
          ${INGITE} checkout boards/${{matrix.board}}/image.yml ${{secrets.CACHE_PATH}}/releases/${{matrix.board}}/${VERSION}/
          ${INGITE} checkout boards/${{matrix.board}}/usr.yml ${{secrets.CACHE_PATH}}/releases/${{matrix.board}}/${VERSION}/
      
      - name: Generate Market data
        run: |-
          ${INGITE} generate-market-data ${{secrets.CACHE_PATH}}/$VERSION/