name: Build and Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+'
    branches:
      - '[0-9]+.x'

env:
  NO_PRINT_PROGRESS: 1
  INGITE: ./ignite

jobs:
  generate-image:
    name: Generate Image
    runs-on: rlxos-server
    timeout-minutes: 47000
    strategy:
      matrix:
        board:
          - amd64
    steps:
      - uses: actions/checkout@v1

      - name: Compiler Ignite
        run: |
          make

      - name: Prerequisties
        run: |
          echo "version: ${GITHUB_REF#refs/*/}" > version.yml

      - name: Generate Element Cache
        run: |
          for element in apps liveconfig usr image ; do
            ${INGITE} build boards/${{matrix.board}}/${element}.yml
          done

      - name: Checkout System Image
        run: |
          ${INGITE} checkout boards/${{matrix.board}}/usr.yml here
          mv here/sysroot.img ${{secrets.CACHE_PATH}}/images/${VERSION}
          gzip -9 ${{secrets.CACHE_PATH}}/images/${VERSION}
          if [[ "refs/tags/" ~= ${GITHUB_REF} ]] ; then
            (cd ${{secrets.CACHE_PATH}}/images; find . -type f -regex '.*[0-9]+\.[0-9]+\.gz' -exec sha256sum {} \;) > ${{secrets.CACHE_PATH}}/images/SHA256SUMS
          else
            (cd ${{secrets.CACHE_PATH}}/images/; zsyncmake -C -U ${{secrets.SERVER_URL}}/images/${VERSION}.gz ${VERSION}.gz)
          fi
          

      - name: Update Installer ISO
        run: |
          ${INGITE} checkout boards/${{matrix.board}}/image.yml ${{secrets.CACHE_PATH}}/releases/${{matrix.board}}

      - name: Generate Market data
        run: |-
          ${INGITE} generate-market-data ${{secrets.CACHE_PATH}}/$VERSION/