name: Build and Release
on:
  push:
    tags:
      - '*'
    branches:
      - 'rolling'
jobs:
  generate-image:
    name: Generate Image
    runs-on: self-hosted
    timeout-minutes: 46000
    strategy:
      matrix:
        board:
          - amd64
    env:
      CACHE_PATH: ${{ secrets.CACHE_PATH }}
      BUILDER: ./builder -cache-path ${{ secrets.CACHE_PATH }}
      SERVER: ${{ secrets.SERVER_URL }}
    steps:
      - uses: actions/checkout@v1

      # - name: Generating Changelog
      #   id: changelog
      #   uses: requarks/changelog-action@v1
      #   with:
      #     token: ${{ github.token }}
      #     tag: ${{ github.ref_name }}

      - name: Setup Environment
        run: |
          TAG_NAME=${GITHUB_REF#refs/*/}
          VERSION=${TAG_NAME%.*}
          CODENAME=${TAG_NAME#${VERSION}.}
          RELEASE="stable"

          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}"   >> $GITHUB_ENV
          echo "CODENAME=${CODENAME}" >> $GITHUB_ENV

          [[ "${TAG_NAME}" -eq "rolling" ]] && RELEASE=0
          echo "RELEASE=${RELEASE}" >> $GITHUB_ENV
          
          echo "
          version: ${VERSION}
          variables:
            release: ${RELEASE}
            codename: ${CODENAME}
            changelog: SOME CHANGES
          " > version.yml

          echo "
          variables:
            server: ${SERVER}
            channel: ${VERSION}
          " > server.yml

      - name: Building pkgupd-builder
        run: |
          go mod tidy
          go mod vendor
          mkdir -p vendor/rlxos/{src,pkg}
          go build -o builder rlxos/cmd/builder

      - name: Generating Board Image
        run: ${BUILDER} build boards/${{matrix.board}}/image.yml

      - name: Generating Updates
        run: ${BUILDER} build boards/${{matrix.board}}/updates.yml
      
      - name: Checkout Updates
        run: ${BUILDER} checkout boards/${{matrix.board}}/updates.yml ${CACHE_PATH}/daily/

      - name: Generating Installer image
        run: |
          ${BUILDER} build boards/${{matrix.board}}/overlay.yml
          ${BUILDER} build boards/${{matrix.board}}/installer.yml
      
      - name: Checkout Installer image
        run: ${BUILDER} checkout boards/${{matrix.board}}/installer.yml ${CACHE_PATH}/daily/

      - name: Create Zync file
        run: |
          cd ${CACHE_PATH}/daily/
          for i in *.img ; do
            zsyncmake -u ${SERVER}/daily/$i $i
          done
