name: Build and Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  generate-image:
    name: Generate Image
    runs-on: self-hosted
    timeout-minutes: 46000
    strategy:
      matrix:
        board:
          - amd64
    env:
      CACHE_PATH: ${{ secrets.CACHE_PATH }}
      SERVER: ${{ secrets.UPDATE_URL }}
      NO_PRINT_PROGRESS: 1
    steps:
      - uses: actions/checkout@v1


      - name: Setup Environment
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          if [[ "${GITHUB_REF}" =~ "refs/heads/" ]] ; then
            CODENAME="experimental"
          else
            CODENAME="stable"
          fi

          echo "ARCH=${{matrix.board}}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}"   >> $GITHUB_ENV
          echo "CODENAME=${CODENAME}" >> $GITHUB_ENV

          echo "NO CHANGELOG" > files/changelog

      - name: Cleanup build cache
        run: make clean

      - name: Make System Image
        run: |
          make cache ELEMENT=boards/${{matrix.board}}/image.yml

      - name: Make Installer ISO
        run: |
          make cache ELEMENT=boards/${{matrix.board}}/installer.yml

      - name: Release System Image
        run: |
          make checkout ELEMENT=boards/${{matrix.board}}/image.yml RELEASE_PATH=${CACHE_PATH}/releases/${CODENAME}

      - name: Release Installer ISO
        run: |
          make checkout ELEMENT=boards/${{matrix.board}}/installer.yml RELEASE_PATH=${CACHE_PATH}/releases/${CODENAME}/${VERSION}

      
      - name: Update Metadata
        run: make metadata RELEASE_PATH=${CACHE_PATH}/releases/${CODENAME}