name: Build Package
on:
  workflow_call:
    inputs:
      recipe_file:
        required: true
        type: string
env:
  NO_INPUT: 1
  PKGUPD_NO_PROGRESS: 1

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 43800
    container:
      image: itsmanjeet/rlxos-devel:2200-1
      volumes:
        - /storage/testing/2200/pkgs/:/var/cache/pkgupd/pkgs/
      options: --privileged
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Update system
        run: |
          export PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml 
          pkgupd update mode.ask=false
          pkgupd install squashfs-tools mode.ask=false
      
      - name: Compile Packages
        run: |
          changed_file="${{inputs.recipe_file}}"
          for recipe in ${changed_file} ; do
            if [[ ${recipe} =~ recipes/ ]] && [[ "${recipe}" == *.yml ]] && [[ -e ${recipe} ]] ; then
              echo "compiling ${recipe}"
              PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml \
                pkgupd build ${PWD}/${recipe} \
                build.repository=$(echo ${recipe} | cut -d '/' -f2)
            fi
          done

      - name: Update Repository
        run: |
          PKGUPD_CONFIG_PATH=${PWD}/pkgupd.testing.yml \
            pkgupd meta