name: build-iso
on:
  push:
    tags:
      '**'
  workflow_dispatch:
    inputs:
      build_id:
        description: 'Build ID'
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 43800

    steps:
      - uses: actions/checkout@v2

      - id: setup-environment-variables
        run: |
          export TAG=${GITHUB_REF#refs/*/}
          echo "VERSION=${TAG%-*}" >> $GITHUB_ENV
          echo "BUILD_ID=${TAG##*-}" >> $GITHUB_ENV
          echo "STORAGE_DIR=/home/itsmanjeet/server/storage/testing/" >> $GITHUB_ENV
          echo "ROOTDIR=/home/itsmanjeet/server/rlxos" >> $GITHUB_ENV

      - id: build-iso
        run: |
          export NO_INPUT=1
          export PKGUPD_NO_PROGRESS=1
          ./scripts/bootstrap.sh --iso --build-id ${BUILD_ID}