name: Build Package
on:
  push:
    paths:
      - "recipes/**"
    branches-ignore:
      - master
  workflow_dispatch:
    inputs:
      recipe_file:
        required: true
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 43800
    container:
      image: itsmanjeet/rlxos-devel:{{env.CONTAINER}}
    
    steps:
      - uses: actions/checkout@v2

      - name: Getting changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1

      - name: Update system
        run: pkgupd update mode.ask=false

      - name: Compile Packages
        run: |
          [[ -n "${{github.event.inputs.recipe_file}}" ]] && changed_file="${{github.event.inputs.recipe_file}}"

          for changed_file in ${{ steps.changed-files.outputs.all }} ; do
            if [[ ${changed_file} =~ "recipes/" ]] && [[ ${changed_file} == "*.yml" ]] && [[ -e ${changed_file} ]] ; then
              echo "compiling ${changed_file}"
              PKGUPD_NO_PROGRESS=1 \
                NO_INPUT=1 \
                pkgupd build ${changed_file}
            fi
          done

