name: build package trigger
on:
  push:
    paths:
      - 'recipes/**'
    branches-ignore:
      - master
  workflow_dispatch:
    inputs:
      recipefile:
        required: true
        type: string
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: get changes
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        if: github.event_name == 'push'

      - name: build changes
        run: |
          export TELEGRAM_TO=${{ secrets.TELEGRAM_TO }}
          export TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          export BAZAAR_ID=${{ secrets.BAZAAR_ID }}
          export BAZAAR_KEY=${{ secrets.BAZAAR_KEY }}
          
          if [[ "${{github.event_name}}" == 'push' ]] ; then
            recipefile="${{steps.changed-files.outputs.all}}"
          else
            recipefile="${{github.event.inputs.recipefile}}"
          fi

          for recipe in ${recipefile} ; do
            if [[ ${recipe} =~ recipes/ ]] && [[ "${recipe}" == *.yml ]] && [[ -e ${recipe} ]] ; then
              ./build.sh build ${recipe} --non-interactive --debug --build-dir /storage/testing/2200/
            fi
          done