name: Build and Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+'
    branches:
      - '[0-9]+.x'

env:
  NO_PRINT_PROGRESS: 1
  INGITE: ./build/ignite

jobs:
  generate-image:
    name: Generate Image
    runs-on: self-hosted
    timeout-minutes: 47000
    strategy:
      matrix:
        board:
          - amd64
    steps:
      - uses: actions/checkout@v1

      - name: Compiler Ignite
        run: |
          make

      - name: Prerequisties
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          echo "version: ${VERSION}" > version.yml
          echo "VERSION=${VERSION}"   >> $GITHUB_ENV

      - name: Generate Element Cache
        run: |
          for element in apps usr image ; do
            ${INGITE} build boards/${{matrix.board}}/${element}.yml
          done

      - name: Checkout System Image
        run: |
          ${INGITE} checkout boards/${{matrix.board}}/usr.yml here
          mv here/sysroot.img ${{secrets.SERVER_REPO_PATH}}/images/${VERSION}
          if [[ "refs/tags/" =~ ${GITHUB_REF} ]] ; then
            zstd -22 ${{secrets.SERVER_REPO_PATH}}/images/${VERSION}
            (cd ${{secrets.SERVER_REPO_PATH}}/images; find . -type f -regex '.*[0-9]+\.[0-9]+\.zst' -exec sha256sum {} \;) > ${{secrets.SERVER_REPO_PATH}}/images/SHA256SUMS
          else
            rm ${{secrets.SERVER_REPO_PATH}}/images/${VERSION}.gz
            gzip -9 ${{secrets.SERVER_REPO_PATH}}/images/${VERSION}
            (cd ${{secrets.SERVER_REPO_PATH}}/images/; zsyncmake -b 2048 -C -U ${{secrets.SERVER_REPO_URL}}/images/${VERSION}.gz ${VERSION}.gz)
          fi
          

      - name: Update Installer ISO
        run: |
          ${INGITE} checkout boards/${{matrix.board}}/image.yml ${{secrets.SERVER_REPO_PATH}}/releases/

      - name: Generate Market data
        run: |-
          ${INGITE} generate-market-data ${{secrets.SERVER_REPO_PATH}}/
