name: Check updates
on:
  schedule:
    - cron: '* 5 * * *'
  workflow_dispatch:

jobs:
  checkup:
    runs-on: self-hosted
    container:
      image: itsmanjeet/rlxos-devel:2200-2
    
    steps:
      - uses: actions/checkout@v2

      - name: check updates
        id: check-updates
        run: |
          ./scripts/check-update.sh 2>&1 | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" | tee run.log
          result_code=${PIPESTATUS[0]}
          echo "::set-output name=result::'$(cat run.log)'"

      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Outdated package report:
            ${{ steps.check-updates.outputs.result }}
          
          