name: package build
on:
  push:
    paths:
      - "recipes/**"
    branches-ignore:
      - master
env:
  BUILD_ID: ${{ github.run_number }}
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 43800

    steps:
      - uses: actions/checkout@v2

      - id: branch-extract
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - id: configure
        name: configuring recipe files
        run: VERSION="${{ steps.branch-extract.outputs.branch }}" STORAGE_DIR=/storage ./scripts/configure.py

      - id: getting-files
        uses: jitterbit/get-changed-files@v1
      
      - id: build-packages
        run: |
          for recipe_file in ${{ steps.getting-files.outputs.all }}; do
            [[ ${recipe_file} =~ "recipes/" ]] || continue
            export PKGUPD_NO_PROGRESS=1
            echo "compiling ${recipe_file}"
            VERSION="${{ steps.branch-extract.outputs.branch }}" \
            NO_INPUT=1 \
            STORAGE_DIR=/home/itsmanjeet/server/storage \
            ROOTDIR=/home/itsmanjeet/server/rlxos \
            ./scripts/pkgupd-build.sh ${recipe_file} force=true
          done
