name: release
on:
  push:
    tags:
      '**'
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 43800

    steps:
      - uses: actions/checkout@v2

      - id: get-tag
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/*/})"

      - id: release
        run: |
          export TAG="${{ steps.get-tag.outputs.tag }}"
          export VERSION=${TAG%-*}
          export BUILD_ID=${TAG##*-}
          export NO_INPUT=1
          export STORAGE_DIR=/home/itsmanjeet/server/storage/testing/
          export PKGUPD_NO_PROGRESS=1
          export ROOTDIR=/home/itsmanjeet/server/rlxos
          ./scripts/bootstrap.sh --iso --docker --build-id ${BUILD_ID}