name: Release
on:
  push:
    tags:
      '**'

env:
  BUILD_ID: ${{ github.run_number }}
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 43800

    steps:
      - uses: actions/checkout@v2

      - id: build-id
        run: echo "BUILD_ID=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - id: release
        run: |
          export VERSION="${{ steps.branch-extract.outputs.branch }}"
          export NO_INPUT=1
          export STORAGE_DIR=/home/itsmanjeet/server/storage/testing/
          export PKGUPD_NO_PROGRESS=1
          export ROOTDIR=/home/itsmanjeet/server/rlxos
          ./scripts/bootstrap.sh --iso --docker --build-id ${{ env.BUILD_ID }}