name: Bootstrap
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 46000
    steps:
      - uses: actions/checkout@v2

      - name: Update PKGUPD
        run: ./bootstrap.py update-pkgupd

      - name: Bootstrap
        run: ./bootstrap.py bootstrap