name: World
on: workflow_dispatch

env:
  BUILD_ID: ${{ github.run_number }}
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 43800

    steps:
      - uses: actions/checkout@v2

      - id: branch-extract
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - id: configure
        name: configuring recipe files
        run: VERSION="${{ steps.branch-extract.outputs.branch }}" STORAGE_DIR=/storage ./scripts/configure.py

      - id: world
        run: |
          export VERSION="${{ steps.branch-extract.outputs.branch }}"
          export NO_INPUT=1
          export STORAGE_DIR=/home/itsmanjeet/server/storage/testing/
          export PKGUPD_NO_PROGRESS=1
          export ROOTDIR=/home/itsmanjeet/server/rlxos
          ./scripts/bootstrap.sh --compile-all