id: kde-gtk-config
version: 5.24.5
about: Plasma kde-gtk-config
depends:
  runtime:
    - kconfigwidgets
    - kdbusaddons
    - kdecoration
    - gtk
    - gsettings-desktop-schemas
  buildtime:
    - extra-cmake-modules
    - sassc
sources:
    - https://download.kde.org/stable/plasma/{{version}}/{{id}}-{{version}}.tar.xz

configure: >
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_TESTING=OFF
    -Wno-dev
